### ISSUE TITLE
Non-Unit Test (NUT) failing on Ubuntu Container due to permission issue

### ISSUE THREAD

**Issue by mcarvin8** [mcarvin8/apex-code-coverage-transformer#43]
I'm attempting to add a non-unit test (NUT) to this repo. I have confirmed this runs locally (windows).

When attempting to push this to the pipeline and use the Salesforce CLI GitHub action for a nut test, it fails on the ubuntu image with `stderr=/bin/sh: 1: /home/runner/work/apex-code-coverage-transformer/apex-code-coverage-transformer/bin/run.js: Permission denied` 

The NUT test is passing on the Windows docker image: https://github.com/mcarvin8/apex-code-coverage-transformer/actions/runs/11221055974

I have the same error on my sf-decomposer plugin when importing the same workflow and writing a NUT test for that plugin.

@renatoliveira - did  you run into this issue at all when making your non-unit test in your plugin? I copied the same YAML you're using for the unit and non-unit tests.

I have also confirmed that the `bin` scripts are the same. 

This seems weird since it's only failing on Ubuntu, but I haven't seen your repo have this issue when I took a look at your tests being ran in a pipeline.

``` yaml
name: tests

on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  unit-tests:
    uses: salesforcecli/github-workflows/.github/workflows/unitTest.yml@main
  nuts:
    needs: unit-tests
    uses: salesforcecli/github-workflows/.github/workflows/nut.yml@main
    secrets: inherit
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    with:
      os: ${{ matrix.os }}
```
